name: JLC Auto Sign

on:
  schedule:
    - cron: '1 16 * * *'  # 北京时间 00:01 启动

  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv pip install --system -r requirements.txt

      - name: Create config
        env:
          TOKEN_LIST: ${{ secrets.TOKEN_LIST }}
          CUSTOMER_CODE_LIST: ${{ secrets.CUSTOMER_CODE_LIST }}
          SEND_KEY: ${{ secrets.SEND_KEY }}
        run: |
          cat > config.py <<EOF
          tokens = """$TOKEN_LIST""".split(",")
          customer_codes = """$CUSTOMER_CODE_LIST""".split(",")
          ACCOUNTS = [{"token": token, "customer_code": customer_codes[index]} for index, token in enumerate(tokens)]
          SEND_KEY = """$SEND_KEY"""
          EOF

      - name: Wait for a random sign-in time
        run: |
          delay=$((RANDOM % 3540))
          echo "Waiting $delay seconds before signing in"
          sleep "$delay"

      - name: Run Sign Script
        env:
          PYTHONUTF8: '1'
          PYTHONUNBUFFERED: '1'
        run: |
          python main.py
